### ISSUE TITLE
VS Code extension issue tracker

### ISSUE THREAD

**Issue by msujew** [TypeFox/open-collaboration-tools#1]
Since work on the VS Code extension is pretty much in progress, we just track everything in one single issue:

- [x] There is currently no way to leave a room except for reloading/closing the window
- [x] Reloading the window closes the connection, but the `collab` workspace stays open. Unless connected to a room, the `collab` workspaces should be removed.
- [x] After losing connection to a workspace, the remote files stay open/visible
- [x] Join requests are currently automatically accepted. Implement a request check (via notification)
- [x] Joining a room has no visual feedback (except for the workspace loading)
- [x] Users are notified of other visible text editor ranges, but can't follow them yet.
- [x] There are presence markers, but without user info. We want to display user names in the editor above their presence marker (similar to live share) @msujew

**Comment by msujew** [comment]
The vscode extension is mostly done by now. New features will receive their own separate issue.
